# ----
# Site

title: UTM
url: "https://proud-alligator.cloudvent.net"
baseurl:
google_analytics_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Virtual machines for Mac
author:
  name: osy
  email: dev@getutm.app
  twitter: UTMapp
social:
  name: Github
  links:
    - https://github.com/utmapp

# -----
# Build

timezone: Etc/UTC

collections:
  virtual_machines:
    output: true
    permalink: /gallery/:name

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "virtual_machines"
    values:
      layout: "virtual_machine"
  -
    scope:
      path: ""
    values:
      layout: "page"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

_comments:
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
